config/routes.rb
Rails.application.routes.draw do

  get 'home/index'

  scope module: 'frontend' do
    resources :home, only: [:index, :new, :create]
    root to: 'home#index'

    get 'contact-us', to: 'home#new', as: 'new_message'
    post 'contact-us', to: 'home#create', as: 'create_message'
    get 'regulations_dp' => 'home#regulations_dp'
    get 'authority_dp' => 'home#authority_dp'
    get 'dp_laws' => 'home#dp_laws'
    get 'search_all' => 'home#search_all'

    get 'home/terms_cond', to: 'home#terms_cond'

    get 'infographics' => 'home#index'


  end

  mount Ckeditor::Engine => '/ckeditor'

  devise_scope :user do
  get 'aubergine', to: 'devise/sessions#new'
end

  devise_for :users, :controllers => { :invitations => 'admin/invitations' }


  root to: 'articles#index'

  resources :articles, only: [:index, :show]

  resources :categories, only: [:index, :show]

  resources :groups, only: [:index, :show]

  namespace :admin do
    resources :articles
    resources :categories
    resources :groups
    resources :infographics, only: %i[index new create destroy]
    resources :users
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html



end

app/models/infographic.rb
class Infographic < ApplicationRecord
	has_attached_file :image
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

	validates :image, presence: true
end

app/controllers/admin/infographics_controller.rb
module Admin
	class InfographicsController < ApplicationController
		before_action :authenticate_user!
		before_action :set_infographic, only: [:destroy]
		def index
			@infographics = Infographic.all
		end

		def new
			@infographic = Infographic.new
		end

		def create
			@infographic = Infographic.new(infographic_params)

			if @infographic.save
				redirect_to admin_infographics_path
			else
				render :new
			end
		end

		def destroy
			@infographic.destroy
			redirect_to admin_infographics_path
		end

		private

		def infographic_params	
				params.require(:infographic).permit(:image)
		end

		def set_infographic
			@infographic = Infographic.find(params[:id])
		end
	end
end

app/views/admin/infographics/index.html.erb
<h2>All Infogrphics</h2>
<strong><%= link_to 'Add New Infographic', new_admin_infographic_path %></strong>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @infographics.each do |infographic| %>
    <tr>
      <td><%= image_tag infographic.image.url, class: 'infographic' %></td>
      <td><%= link_to 'Delete', admin_infographic_path(infographic), method: :delete, data: { confirm: 'Are you sure you want to delete this?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/infographics/new.html.erb
<%= form_for([:admin, @infographic], url: admin_infographics_path, html: { multipart: true }) do |f| %>
  <% if @infographic.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @infographic.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form__row">
    <%= f.label :image %>
    <div>
      <%= f.file_field :image %>
    </div>
  </div>

  <%= f.hidden_field :created_at %>

  <div class="form__row">
    <%= f.submit class: "button" %>
  </div>
<% end %>