config/routes.rb
Rails.application.routes.draw do

  get 'home/index'

  scope module: 'frontend' do
    resources :home, only: [:index, :new, :create]
    root to: 'home#index'

    get 'contact-us', to: 'home#new', as: 'new_message'
    post 'contact-us', to: 'home#create', as: 'create_message'
    get 'regulations_dp' => 'home#regulations_dp'
    get 'authority_dp' => 'home#authority_dp'
    get 'dp_laws' => 'home#dp_laws'
    get 'search_all' => 'home#search_all'

    get 'home/terms_cond', to: 'home#terms_cond'

    get 'infographics' => 'home#index'


  end

  mount Ckeditor::Engine => '/ckeditor'

  devise_scope :user do
  get 'aubergine', to: 'devise/sessions#new'
end

  devise_for :users, :controllers => { :invitations => 'admin/invitations' }


  root to: 'articles#index'

  resources :articles, only: [:index, :show]

  resources :categories, only: [:index, :show]

  resources :groups, only: [:index, :show]

  namespace :admin do
    resources :articles
    resources :categories
    resources :groups
    resources :infographics, only: %i[index new create destroy]
    resources :users
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html



end

app/controllers/frontend/articles_controller.rb
class Frontend::ArticlesController < FrontendController

  before_action :set_article, only: [:show]
  load_and_authorize_resource

  # GET /articles
  # GET /articles.json
  def index
    if params[:search]
      @articles = Article.where(published: true).all.search(params[:search])
    else
      @articles = Article.where(published: true).all
    end
    @categories = Category.all
    @groups = Group.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    render "show.json"
    #render json: @article
  end

  private
    def set_article
      @article = Article.where(published: true).find(params[:id])
        # catch error when someone changes article_ID in the url.
        rescue ActiveRecord::RecordNotFound
        flash[:notice] = "The selected ID is currenlty not publicly available."
        redirect_back fallback_location: articles_url
    end

end

app/controllers/frontend/home_controller.rb
class Frontend::HomeController < FrontendController

  def index
    @message = Message.new
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)

    if @message.valid?
      MessageMailer.contact_us(@message).deliver_now
      redirect_to root_path(anchor: 'contact_link') , notice: "Thank you for contacting us, we'll get back to you soon"
    else
      redirect_to root_path(anchor: 'contact_link') , notice: "Message not sent. Please fill out all fields."
    end
  end

  def dp_laws
        @articles = []
    categories=Category.where('group_id = 1')
    categories.each do |category|
      articles=Article.where(category_id: category.id).where(published: true).order(number: :asc)
      @articles += articles
    end

    @groups=Group.all
  end

  def authority_dp
        @articles = []
    categories=Category.where('group_id = 2')
    categories.each do |category|
      articles=Article.where(category_id: category.id).where(published: true).order(number: :asc)
      @articles += articles
    end

    @groups=Group.all
  end

  def regulations_dp
  	@articles = []
  	categories=Category.where('group_id = 3')
  	categories.each do |category|
  		articles=Article.where(category_id: category.id).where(published: true).order(number: :asc)
  		@articles += articles
  	end

    @groups=Group.all
  end

  def Infographic
    
  end

  def search_all
    @articles = Article.search(params[:search]).where(published: true)
    pp @articles
    # group by group_id going via category_id
    # .sort_by(group.id)
    objects = Group.all.map do |group|
      OpenStruct.new(id: group.id, title: group.title)
    end
    @objects = objects.map do |object|
      object.categories = Category.where(group_id: object.id).map do |category|
        OpenStruct.new(
          # category: category,
          category: category,

          articles: @articles.where(category_id: category.id)
        )
      end
      object
    end
    # pp @objects
  end

  def terms_cond
  end

  private

  def message_params

     message_params = params.require(:message).permit(:full_name, :email, :body, :subject_line)

  end
end

app/controllers/frontend_controller.rb
class FrontendController < ApplicationController
	layout 'frontend/application'
end

app/helpers/frontend/home_helper.rb
module Frontend::HomeHelper
end

app/views/layouts/frontend/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jersey ICO<%= " | " + yield(:title) if content_for?(:title) %></title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= csrf_meta_tags %>

    <link href="https://fonts.googleapis.com/css?family=Space+Mono" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">

    <% unless current_page?(root_path) %>
      <%= stylesheet_link_tag    'frontend#frontend', media: 'all', 'data-turbolinks-track': 'reload' %>
    <% else %>
      <%= stylesheet_link_tag    'index#index', media: 'all', 'data-turbolinks-track': 'reload' %>
    <% end %>


    <%= javascript_include_tag 'frontend', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://unpkg.com/flickity@2/dist/flickity.min.css">
    <script>
      if (screen && screen.width < 500) {
        document.write('<script src="https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js"><\/script>');
      }
    </script>

  </head>
  <body>
    <nav class="mainNav">
      <% unless current_page?(root_path) %>
        <%= link_to(image_tag("frontend/JSY_transparent_white.png", class: "logo"), root_path ) %>
      <% else %>
        <%= link_to(image_tag("frontend/JSY_transparent.png", class: "logo"), root_path ) %>
      <% end %>
      <ul class="linksContainer">
        <li><%= link_to 'LAWS', '/dp_laws', class: 'link' %></li>
        <li><%= link_to 'ABOUT', root_path(anchor: 'about_link'), class: 'link' %></li>
        <li><%= link_to 'CONTACT', root_path(anchor: 'contact_link'), class: 'link' %></li>
      </ul>


        <%= form_tag(search_all_path, :method => "get", id: "search-form", class: "searchForm")  do %>
          <%= text_field_tag :search, params[:search], placeholder: "Search all articles" , class: "searchField"  %>
          <%= submit_tag "Search", :name => nil, class: "searchButton" %>
        <% end %>

        <% unless current_page?(root_path) %>
          <%= image_tag("frontend/bars.svg", class: "hamburger") %>
        <% else %>
          <%= image_tag("frontend/bars_red.svg", class: "hamburger") %>
        <% end %>

    </nav>

    <nav class="mobileNav">

      <ul class="linksContainerMobile">
        <li><%= link_to 'DATA PROTECTION (JERSEY) LAW 2018', '/dp_laws' %></li>
        <li><%= link_to 'DATA PROTECTION AUTHORITY (JERSEY) LAW 2018', '/authority_dp' %></li>
        <li><%= link_to 'DATA PROTECTION (REGISTRATION AND CHARGES) (JERSEY) REGULATIONS 2018', '/regulations_dp' %></li>
      </ul>

    </nav>

    <%= yield %>
    <footer>
      <p><%= link_to 'Privacy Notice', home_terms_cond_path %> | Jersey ICO Copyright <%= Time.current.year %></p>
    </footer>

<!--add a sign out alert  -->

    <% if flash[:alert] || flash[:notice] || flash[:error] || flash[:success] %>
      <div class="container">
        <div class="row">
          <% if flash[:error] %>
            <div class="col-md-10 mx-auto mt-3">
              <div class="oaerror danger alert text-center">
                    <strong>Error  </strong><%= flash[:error] %></div>
            </div>
          <% end %>

          <% if flash[:alert] %>
            <div class="col-md-10 mx-auto mt-3">
              <div class="oaerror warning alert text-center">
                    <strong>Warning  </strong><%= flash[:alert] %></div>
            </div>
          <% end %>

          <% if flash[:notice] %>
            <div class="col-md-10 mx-auto mt-3">
              <div class="oaerror info alert text-center">
                    <strong>Note  </strong><%= flash[:notice] %></div>
            </div>
          <% end %>

          <% if flash[:success] %>
            <div class="col-md-10 mx-auto mt-3">
              <div class="oaerror success alert text-center">
                    <strong>Success  </strong><%= flash[:success] %></div>
            </div>
          <% end %>

        </div>
      </div>
    <% end %>
  </body>
</html>