config/routes.rb
Rails.application.routes.draw do

  get 'home/index'

  scope module: 'frontend' do
    resources :home, only: [:index, :new, :create]
    root to: 'home#index'

    get 'contact-us', to: 'home#new', as: 'new_message'
    post 'contact-us', to: 'home#create', as: 'create_message'
    get 'regulations_dp' => 'home#regulations_dp'
    get 'authority_dp' => 'home#authority_dp'
    get 'dp_laws' => 'home#dp_laws'
    get 'search_all' => 'home#search_all'

    get 'home/terms_cond', to: 'home#terms_cond'

    get 'infographics' => 'home#index'


  end

  mount Ckeditor::Engine => '/ckeditor'

  devise_scope :user do
  get 'aubergine', to: 'devise/sessions#new'
end

  devise_for :users, :controllers => { :invitations => 'admin/invitations' }


  root to: 'articles#index'

  resources :articles, only: [:index, :show]

  resources :categories, only: [:index, :show]

  resources :groups, only: [:index, :show]

  namespace :admin do
    resources :articles
    resources :categories
    resources :groups
    resources :infographics, only: %i[index new create destroy]
    resources :users
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html



end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :group
  has_many :articles
  #an artuicle acn belong to multiuple catogories

  def self.search(search)
      where("title LIKE ?", "%#{search}%")
  end

end

app/models/category_type.rb
class CategoryType < ApplicationRecord
  belongs_to :category
  # an article can belong to multiple categories

  validates_uniqueness_of :category_type_desc, :message => '%{value} already exists.'

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController

	before_action :authenticate_user!
  before_action :set_category, only: [:show]
  load_and_authorize_resource

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

	def index
		if params[:search]
			@categories = Category.search(params[:search])
		else
			@categories = Category.all
		end
	end

  # GET /categories/1
  # GET /categories/1.json
  def show
		  @articles = Article.all
  end

  # GET /categories/new
  def new
    @category = Category.new
    @categories = Category.all
    @groups = Group.all
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to admin_categories_path(@category), notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to admin_categories_path, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to admin_categories_path, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title, :group_id)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :set_category, only: [:show]
  load_and_authorize_resource

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_category-articles.html.erb
<table class="indexTable">
  <thead>
    <tr>

      <th class="thPublished">Published</th>
      <th class="thTitle">Title</th>
      <th class="thContent">Content</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% Article.all.where(category_id: @category.id).each do |article|  %>
      <tr class="rowAlternateColor">

        <% if article.published %>
          <td> published </td>
        <% else %>
          <td> Unpublished </td>
        <% end %>
        <td> <%= article.title %> </td>
        <td> <%= article.content.truncate(17) %> </td>
        
        <td class="showEditDestroyColumns"><%= link_to 'Show', admin_article_path(article) %></td>
        <td class="showEditDestroyColumns"><%= link_to 'Edit', edit_admin_article_path(article, scope: article.category.group) %></td>
        <td class="showEditDestroyColumns"><%= link_to 'Destroy', admin_article_path(article), method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>

  </tbody>
</table>

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category] do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :category_title %>
  </div>


  <div class="field">
    <%= form.label :group_id %>
    <%= form.select :group_id,
    options_for_select(Group.all.map { |group| [group.title, group.id] }),
    { prompt: true }
    %>

  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', admin_categories_path %>

app/views/admin/categories/index.html.erb
<h1>Categories</h1>


<%= form_tag admin_categories_path, method: :get, id: "search-form", style: 'margin-bottom: 20px' do %>
  <div class="row row-align-center">
    <%= text_field_tag(
      :search,
      params[:search],
      placeholder: "Search Categories",
      style: 'padding: 10px 15px; font-size: 16px; width:50%')
    %>
    <%= submit_tag "Search", :name => nil, class: 'button' %>
  </div>

<% end %>


<%= link_to 'Add New Category', new_admin_category_path %>

<table class="indexTable" style="width:100%">
  <thead>
    <tr>
      <th class="thTitle">Title</th>
      <th class="thContent">Group</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr class="rowAlternateColor">
        <td><%= category.title.titleize %></td>
        <td><%= category.group.title.titleize %></td>
        <td class="showEditDestroyColumns"><%= link_to 'Show', admin_category_path(category), class: 'link' %></td>
        <td class="showEditDestroyColumns"><%= link_to 'Edit', edit_admin_category_path(category), class: 'link' %></td>
        <td class="showEditDestroyColumns"><%= link_to 'Destroy', admin_category_path(category), class: 'link', method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/admin/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', admin_categories_path %>

app/views/admin/categories/show.html.erb
<div class="showArea">

<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<p>
  <strong class="showHeading">Group:</strong>
  <%= @category.group.title %>
</p>

<p>
  <strong class="showHeading">Title:</strong>
  <%= @category.title %>
</p>

<%= link_to 'Edit', edit_admin_category_path(@category) %> |
<%= link_to 'Back', admin_categories_path %>

<%= render 'category-articles'%>


</div>