config/routes.rb
Rails.application.routes.draw do

  get 'home/index'

  scope module: 'frontend' do
    resources :home, only: [:index, :new, :create]
    root to: 'home#index'

    get 'contact-us', to: 'home#new', as: 'new_message'
    post 'contact-us', to: 'home#create', as: 'create_message'
    get 'regulations_dp' => 'home#regulations_dp'
    get 'authority_dp' => 'home#authority_dp'
    get 'dp_laws' => 'home#dp_laws'
    get 'search_all' => 'home#search_all'

    get 'home/terms_cond', to: 'home#terms_cond'

    get 'infographics' => 'home#index'


  end

  mount Ckeditor::Engine => '/ckeditor'

  devise_scope :user do
  get 'aubergine', to: 'devise/sessions#new'
end

  devise_for :users, :controllers => { :invitations => 'admin/invitations' }


  root to: 'articles#index'

  resources :articles, only: [:index, :show]

  resources :categories, only: [:index, :show]

  resources :groups, only: [:index, :show]

  namespace :admin do
    resources :articles
    resources :categories
    resources :groups
    resources :infographics, only: %i[index new create destroy]
    resources :users
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :confirmable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable, :invitable

  validate :password_complexity
  
  def password_complexity
  
    return if password.blank? || password =~ /^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*(_|[^\w])).{8,128}$/

    errors.add :password, ' must include at least: 1 upper case letter, 1 lower case letter, 1 digit and 1 symbol'
  
 end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  def index
    @users = User.all.order('last_sign_in_at DESC')
  end

  def show
  end

  def update
    if @user.update(user_params)
        flash[:notice] = 'User Updated'
        redirect_to admin_users_path
    else
      render 'new'
    end
  end

  def edit
  end

  def destroy
    @user.destroy
    flash[:notice] = "User Removed"
    redirect_to admin_users_path
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email, :first_name, :last_name, :manager)
    end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/create.html.erb
<h1>Admin::Users#create</h1>
<p>Find me in app/views/admin/users/create.html.erb</p>

app/views/admin/users/destroy.html.erb
<h1>Admin::Users#destroy</h1>
<p>Find me in app/views/admin/users/destroy.html.erb</p>

app/views/admin/users/edit.html.erb
<h2>Edit User</h2>

<%= form_for [:admin, @user] do |f| %>
	
	<div>
		<%= f.label :email %>
		<%= f.text_field :email %>
	</div>

	<div>
		<%= f.label :Forename %>
		<%= f.text_field :first_name %>
	</div>

	<div>
		<%= f.label :Surname %>
		<%= f.text_field :last_name %>
	</div>

	<div>
		<% if current_user.manager? %>
			<%= f.label :Manager? %>
			<%= f.check_box :manager %>
		<% end %>
	</div>

		<%= f.submit "Submit" %>
		<%= link_to "Cancel", admin_user_path(params[:id]) %>
<% end %>

<%=  button_to 'Delete User', admin_user_path(params[:id]), :method => :delete %>

app/views/admin/users/index.html.erb
<div class="signinPage">

	<% @users.each do |user| %>
		<br>
		<%= link_to user.email, admin_user_path(user)  %></td>
		<br>
		<p>Joined on: <%= user.created_at.to_time.strftime('%e %B %Y') %></p>
		<br>
	<% end %>

</div>


<% if current_user.manager? %>
	<%= link_to "Invite New User", new_user_invitation_path  %>
<% end %>

app/views/admin/users/show.html.erb
<p>Email: <%= @user.email %></p>
<p>Joined on: <%= @user.created_at %></p>

<% if current_user.manager? %>
	<%= button_to "Edit User", edit_admin_user_path(@user), :method => :get %>
<% end %>

app/views/admin/users/update.html.erb
<h1>Admin::Users#update</h1>
<p>Find me in app/views/admin/users/update.html.erb</p>